### ISSUE TITLE
Integrate the OpenSea API into 3box-activity

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-activity#13]
# Description
As a 3Box developer I need an easy way to get all the ERC721s owned by an account, along with all the other nifty metadata, so that we can display it in our dapp on the "Collectibles" page.

# Resources
https://docs.opensea.io/reference#api-overview

**Comment by oed** [comment]
How about we just do it in the app directly? Seems like there is no benefit to having a wrapping library at this point.
