### ISSUE TITLE
Enable getProfile for addresses in the activity feed

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-activity#14]

**Comment by oed** [comment]
What does this have to do with 3box-activity? Should happen in the dapp imo.

**Comment by oed** [comment]
If in the dapp it could load and display ethereum addresses first, then show image and name once they are loaded.

**Comment by michaelsena** [comment]
Issue moved to [3box/3box-dapp #246](https://github.com/3box/3box-dapp/issues/246) via [**ZenHub**](https://www.zenhub.com/)
